name: cleanup
description: cleanup code 'src' directory
runs:
  using: docker
  image: "gcr.io/weave-lab/devx/go-builder:1.17.2-stable"
  entrypoint: /bin/sh
  args:
    - -e
    - -c
    - |
      mkdir TO_DELETE || true
      rm -rf TO_DELETE/actions || true
      mv * TO_DELETE > /dev/null 2>&1 || true
      mv TO_DELETE/actions .
      rm -rf TO_DELETE