on:
  workflow_call:
    secrets:
      SCAN_TOKEN:
        required: true
      GITHUBACTIONSTOKEN:
        required: true
jobs:
  semgrep:
    name: Semgrep
    runs-on: [ self-hosted, weave-stable ]
    if: ${{ github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' }}
    steps:
      - name: Cleanup
        uses: docker://gcr.io/weave-lab/devx/github-actions-cleanup:stable
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: look at dir
        run: |
          echo "== pwd"
          pwd
          echo "== .numen/deploy/"
          ls -l .numen/deploy/
          echo "== .numen/"
          ls -l .numen/
          echo "== ."
          ls -la
          echo "== .submodules"
          ls -l .submodules
