on:
  workflow_call:
    secrets:
      SCAN_TOKEN:
        required: true
      GITHUBACTIONSTOKEN:
        required: true
jobs:
  semgrep:
    name: Semgrep
    runs-on: [ self-hosted, weave-stable ]
    steps:
      - name: Checkout Actions Repo
        uses: actions/checkout@v2
        with:
          repository: weave-lab/actions
          token: ${{secrets.GITHUBACTIONSTOKEN}}
          path: actions
          persist-credentials: false
      - name: Cleanup
        uses: ./actions/cleanup/
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SCAN_TOKEN }}
