on:
  workflow_call:
    secrets:
      SCAN_TOKEN:
        required: true
      GITHUBACTIONSTOKEN:
        required: true
    git:
      submodules:
        default: false

jobs:
  semgrep:
    name: Semgrep
    runs-on: [ self-hosted, weave-stable ]
    if: ${{ github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' }}
    steps:
      - name: Cleanup
        uses: docker://gcr.io/weave-lab/devx/github-actions-cleanup:stable
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          submodules: ${{ git.submodules }}
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SCAN_TOKEN }}
