on:
  workflow_call:
    secrets:
      SCAN_TOKEN:
        required: true
      GITHUBACTIONSTOKEN:
        required: true
    inputs:
      submodules:
        description: 'Enable submodule (recursive) checkout by actions/checkout'
        # Allowed values are "" or "false" (default), "true" and "recursive" - see https://github.com/actions/checkout/blob/main/README.md#usage
        type: string
        required: false

jobs:
  semgrep:
    name: Semgrep
    runs-on: [ self-hosted, weave-stable ]
    if: ${{ github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' }}
    steps:
      - name: Cleanup
        uses: docker://gcr.io/weave-lab/devx/github-actions-cleanup:stable
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          submodules: ${{ inputs.submodules }}
      - uses: returntocorp/semgrep-action@v1
        continue-on-error: true
        with:
          publishToken: ${{ secrets.SCAN_TOKEN }}
